panda_arm:

  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3

# kinematics_solver: FABRIK_kinematics/FABRIKKinematicsPlugin
# kinematics_solver_timeout: 0.005
# solve_type: Speed

